# Generated by Django 4.0.4 on 2022-05-27 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('likes', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('likes', models.PositiveIntegerField()),
                ('comment_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_comments', to='threads.comment')),
                ('post_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_level_comments', to='threads.thread')),
            ],
        ),
    ]
